### ISSUE TITLE
Sequence Aborted with error 0:SUB_ERROR_NONE

### ISSUE THREAD

**Issue by Louis2099** [Kinovarobotics/ros_kortex#333] opened 2024-08-24 01:12 UTC
HI I'm student using kinova kortex python API on a gen3 7dof robot arm, my settings are listed as following:
kortex 2.6.0.post3
frimware 2.5.2-1

The problem I've been experiencing is that, I'm using the sequence example "api_python/examples/102-Movement_high_level/02-sequence.py" by adding a series of "move to Cartesian position" actions, following is one of my example trajectories:
"""
example_traj = ([0.28747064, 0.04720456, 1.03254818]), 
        np.array([0.40148122, 0.01917565, 0.96486813]), 
        np.array([ 0.52025528, -0.02537908,  0.86594063]), 
        np.array([ 0.63002006, -0.08680653,  0.72415356]), 
        np.array([ 0.70775769, -0.16291518,  0.53187928]), 
        np.array([ 0.72229969, -0.24377655,  0.29120655]), 
        np.array([ 0.55527246, -0.35700423,  0.15574953])
"""
But I always got error message that shows:
"Sequence aborted with error 0:SUB_ERROR_NONE"

I cannot find useful information to resolve the issue, my guess is that the trajectory has certain kind of limitations, thus not all action sequences can be executed?

I'd be appreciated if you can help resolve this issue.

**Comment by martinleroux** [comment] 2024-09-11 13:59
I remember answering this issue either via support or in the correct repo. Anyone looking at this in the future, the issue is that most of these points are outside the reach of the robot.

I will be closing this issue since it is raised in the wrong repo.

**Closed as completed by martinleroux** 2024-09-11 13:59 UTC
