### ISSUE TITLE
Missing head file, catkin_make failed

### ISSUE THREAD

**Issue by kracon7** [Kinovarobotics/ros_kortex#10] opened 2019-03-21 03:36 UTC
I'm using Ubuntu 16.04 and ROS kinetic

First, I followed the procedure to setup "kortex" repository from: https://github.com/Kinovarobotics/kortex.
I followed the following directory hierarchies:
```sh
examples/kortex_api  
┬  
├ include/
├ lib/  
└   ┬  
    ├ debug/  
    └ release/ 
```

Here's what I got after cmake installation:
```sh
jc@jc-Precision-5510:/opt/kortex-master/api_cpp/examples/build$ sudo cmake .. -DCMAKE_BUILD_TYPE=release
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
---------------------------------------------------------------------------------
Project 'Getting_started' args: 
Project building for: 'Linux' in 'release' mode
create TARGET_EXE_NAME: '01_api_creation'
create TARGET_EXE_NAME: '02-protobuf_object_manipulation'
create TARGET_EXE_NAME: '03_api_mechanism'
create TARGET_EXE_NAME: '04_error_management'
create TARGET_EXE_NAME: '05_notification'
---------------------------------------------------------------------------------
Project 'Getting_started' args: 
Project building for: 'Linux' in 'release' mode
create TARGET_EXE_NAME: '01_devices_routing'
---------------------------------------------------------------------------------
Project 'Getting_started' args: 
Project building for: 'Linux' in 'release' mode
create TARGET_EXE_NAME: '01-move_angular_and_cartesian'
create TARGET_EXE_NAME: '02-sequence'
---------------------------------------------------------------------------------
Project 'Getting_started' args: 
Project building for: 'Linux' in 'release' mode
create TARGET_EXE_NAME: '01-low_level_cyclic'
CMake Error at CMakeLists.txt:29 (add_subdirectory):
  add_subdirectory given source "300-BaseGen3_low_level_bypass" which is not
  an existing directory.


---------------------------------------------------------------------------------
Project 'Getting_started' args: 
Project building for: 'Linux' in 'release' mode
create TARGET_EXE_NAME: '01_vision'
-- Configuring incomplete, errors occurred!
See also "/opt/kortex-master/api_cpp/examples/build/CMakeFiles/CMakeOutput.log".
jc@jc-Precision-5510:/opt/kortex-master/api_cpp/examples/build$ make
make: *** No targets specified and no makefile found.  Stop.
jc@jc-Precision-5510:/opt/kortex-master/api_cpp/examples/build$ sudo make
make: *** No targets specified and no makefile found.  Stop.

```

Then I followed the instruction to install protobuf. No problem found expect for the same problem as [issue 5315](https://github.com/protocolbuffers/protobuf/issues/5315). Installation was successful after removing -Werror from src/Makefile

These are what I did before git clone the kortex-ros directory and ran cankin_make.
Any ideas where I did incorrectly or if it is a bug? Thanks!

```
/home/jc/catkin_ws/src/ros_kortex/kortex_examples/cpp/example_get_sensor_settings.cpp:2:59: fatal error: kortex_vision_config_driver/GetSensorSettings.h: No such file or directory
compilation terminated.
ros_kortex/kortex_examples/CMakeFiles/GetSensorSettings.dir/build.make:62: recipe for target 'ros_kortex/kortex_examples/CMakeFiles/GetSensorSettings.dir/cpp/example_get_sensor_settings.cpp.o' failed
make[2]: *** [ros_kortex/kortex_examples/CMakeFiles/GetSensorSettings.dir/cpp/example_get_sensor_settings.cpp.o] Error 1
CMakeFiles/Makefile2:22442: recipe for target 'ros_kortex/kortex_examples/CMakeFiles/GetSensorSettings.dir/all' failed
make[1]: *** [ros_kortex/kortex_examples/CMakeFiles/GetSensorSettings.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/jc/catkin_ws/src/ros_kortex/kortex_examples/cpp/example_play_cartesian.cpp:2:51: fatal error: kortex_driver/PlayCartesianTrajectory.h: No such file or directory
compilation terminated.
ros_kortex/kortex_examples/CMakeFiles/PlayCartesian.dir/build.make:62: recipe for target 'ros_kortex/kortex_examples/CMakeFiles/PlayCartesian.dir/cpp/example_play_cartesian.cpp.o' failed
make[2]: *** [ros_kortex/kortex_examples/CMakeFiles/PlayCartesian.dir/cpp/example_play_cartesian.cpp.o] Error 1
CMakeFiles/Makefile2:22516: recipe for target 'ros_kortex/kortex_examples/CMakeFiles/PlayCartesian.dir/all' failed
make[1]: *** [ros_kortex/kortex_examples/CMakeFiles/PlayCartesian.dir/all] Error 2
[ 18%] Generating Javascript code from kortex_device_manager/Unit.msg
/home/jc/catkin_ws/src/ros_kortex/kortex_examples/cpp/example_play_cartesian_position.cpp:2:59: fatal error: kortex_driver/PlayCartesianTrajectoryPosition.h: No such file or directory
compilation terminated.
[ 18%] Generating Javascript code from kortex_device_manager/IPv4Settings.msg
ros_kortex/kortex_examples/CMakeFiles/PlayCartesianPosition.dir/build.make:62: recipe for target 'ros_kortex/kortex_examples/CMakeFiles/PlayCartesianPosition.dir/cpp/example_play_cartesian_position.cpp.o' failed
make[2]: *** [ros_kortex/kortex_examples/CMakeFiles/PlayCartesianPosition.dir/cpp/example_play_cartesian_position.cpp.o] Error 1
CMakeFiles/Makefile2:22479: recipe for target 'ros_kortex/kortex_examples/CMakeFiles/PlayCartesianPosition.dir/all' failed
make[1]: *** [ros_kortex/kortex_examples/CMakeFiles/PlayCartesianPosition.dir/all] Error 2
[ 18%] Generating Python from MSG kortex_device_manager/SafetyLimitType
[ 18%] Generating Python from MSG kortex_device_manager/SafetyConfiguration
[ 18%] Generating Javascript code from kortex_device_manager/PowerOnSelfTestResult.msg
[ 19%] Generating Javascript code from kortex_device_manager/ServiceVersion.msg
[ 19%] Generating Javascript code from kortex_device_manager/PartNumberRevision.msg
[ 19%] Generating Javascript code from kortex_device_manager/Empty.msg
[ 19%] Generating Python from MSG kortex_device_manager/FirmwareVersion
[ 19%] Generating Javascript code from kortex_device_manager/SerialNumber.msg
[ 19%] Generating Javascript code from kortex_device_manager/NotificationOptions.msg
[ 19%] Generating Javascript code from kortex_device_manager/SafetyNotification.msg
[ 19%] Generating Javascript code from kortex_device_manager/SafetyHandle.msg
[ 19%] Generating Javascript code from kortex_device_manager/SafetyStatusValue.msg
[ 19%] Generating Javascript code from kortex_device_manager/Timestamp.msg
[ 19%] Generating Javascript code from kortex_device_manager/ModelNumber.msg
[ 19%] Generating Python from MSG kortex_device_manager/Unit
[ 19%] Generating Javascript code from kortex_device_manager/NotificationHandle.msg
[ 19%] Generating Python from MSG kortex_device_manager/IPv4Settings
[ 19%] Generating Python from MSG kortex_device_manager/PowerOnSelfTestResult
[ 19%] Generating Javascript code from kortex_device_manager/SafetyThreshold.msg
[ 19%] Generating Javascript code from kortex_device_manager/ArmState.msg
[ 19%] Generating Python from MSG kortex_device_manager/ServiceVersion
[ 19%] Generating Javascript code from kortex_device_manager/BootloaderVersion.msg
[ 19%] Generating Javascript code from kortex_device_manager/SafetyEnable.msg
[ 19%] Generating Javascript code from kortex_device_manager/SafetyInformation.msg
[ 19%] Generating Python from MSG kortex_device_manager/PartNumberRevision
[ 19%] Generating Javascript code from kortex_device_manager/NotificationType.msg
[ 19%] Generating Javascript code from kortex_device_manager/SafetyStatus.msg
[ 19%] Generating Python from MSG kortex_device_manager/Empty
[ 19%] Generating Javascript code from kortex_device_manager/DeviceType.msg
[ 19%] Generating Python from MSG kortex_device_manager/SerialNumber
[ 19%] Generating Javascript code from kortex_device_manager/RebootRqst.msg
[ 19%] Generating Javascript code from kortex_device_manager/Connection.msg
[ 19%] Generating Python from MSG kortex_device_manager/NotificationOptions
[ 19%] Generating Python from MSG kortex_device_manager/SafetyNotification
[ 19%] Generating Javascript code from kortex_device_manager/RunModes.msg
[ 19%] Generating Javascript code from kortex_device_manager/DeviceHandle.msg
[ 19%] Generating Python from MSG kortex_device_manager/SafetyHandle
[ 20%] Generating Python from MSG kortex_device_manager/SafetyStatusValue
[ 20%] Generating Javascript code from kortex_device_manager/UserProfileHandle.msg
[ 20%] Generating Python from MSG kortex_device_manager/Timestamp
[ 20%] Generating Javascript code from kortex_device_manager/RunMode.msg
[ 20%] Generating Javascript code from kortex_device_manager/Permission.msg
[ 20%] Generating Python from MSG kortex_device_manager/ModelNumber
[ 20%] Generating Python from MSG kortex_device_manager/NotificationHandle
[ 20%] Generating Python from MSG kortex_device_manager/SafetyThreshold
[ 20%] Generating Python from MSG kortex_device_manager/ArmState
[ 20%] Generating Javascript code from kortex_device_manager/SafetyInformationList.msg
[ 20%] Linking CXX executable /home/jc/catkin_ws/devel/lib/kortex_examples/SetControlLoopParameters
[ 20%] Linking CXX executable /home/jc/catkin_ws/devel/lib/kortex_examples/GetControlLoopParameters
[ 20%] Linking CXX executable /home/jc/catkin_ws/devel/lib/kortex_examples/ReadAllDevices
[ 20%] Generating Python from MSG kortex_device_manager/SafetyEnable
[ 20%] Generating Python from MSG kortex_device_manager/BootloaderVersion
[ 20%] Generating Python from MSG kortex_device_manager/SafetyInformation
[ 21%] Generating Javascript code from kortex_device_manager/DeviceHandles.msg
[ 21%] Generating Javascript code from kortex_device_manager/KortexError.msg
[ 21%] Generating Javascript code from kortex_device_manager/SetRunMode.srv
[ 21%] Generating Javascript code from kortex_device_manager/GetFirmwareVersion.srv
[ 21%] Generating Javascript code from kortex_device_manager/SetPartNumber.srv
[ 21%] Generating Python from MSG kortex_device_manager/NotificationType
[ 21%] Generating Python from MSG kortex_device_manager/SafetyStatus
[ 21%] Generating Python from MSG kortex_device_manager/DeviceType
[ 21%] Built target ReadAllDevices
[ 21%] Generating Javascript code from kortex_device_manager/ClearSafetyStatus.srv
[ 21%] Built target GetControlLoopParameters
[ 21%] Generating Javascript code from kortex_device_manager/SetPartNumberRevision.srv
[ 21%] Built target SetControlLoopParameters
[ 21%] Generating Python from MSG kortex_device_manager/RebootRqst
[ 21%] Generating Javascript code from kortex_device_manager/SetIPv4Settings.srv
[ 21%] Generating Javascript code from kortex_device_manager/GetSafetyInformation.srv
[ 21%] Generating Python from MSG kortex_device_manager/Connection
[ 21%] Generating Python from MSG kortex_device_manager/RunModes
[ 21%] Generating Javascript code from kortex_device_manager/ResetSafetyDefaults.srv
[ 21%] Generating Javascript code from kortex_device_manager/ClearAllSafetyStatus.srv
[ 21%] Generating Python from MSG kortex_device_manager/DeviceHandle
[ 21%] Generating Javascript code from kortex_device_manager/GetIPv4Settings.srv
[ 21%] Generating Python from MSG kortex_device_manager/UserProfileHandle
[ 21%] Generating Python from MSG kortex_device_manager/RunMode
[ 21%] Generating Javascript code from kortex_device_manager/GetRunMode.srv
[ 21%] Generating Python from MSG kortex_device_manager/Permission
[ 21%] Generating Python from MSG kortex_device_manager/SafetyInformationList
[ 21%] Generating Javascript code from kortex_device_manager/GetMACAddress.srv
[ 21%] Generating Python from MSG kortex_device_manager/DeviceHandles
[ 21%] Generating Javascript code from kortex_device_manager/SetSafetyEnable.srv
[ 21%] Generating Python from MSG kortex_device_manager/KortexError
[ 21%] Generating Python code from SRV kortex_device_manager/SetRunMode
[ 21%] Generating Python code from SRV kortex_device_manager/GetFirmwareVersion
[ 21%] Generating Javascript code from kortex_device_manager/GetAllSafetyConfiguration.srv
[ 21%] Generating Python code from SRV kortex_device_manager/SetPartNumber
[ 21%] Generating Python code from SRV kortex_device_manager/ClearSafetyStatus
[ 21%] Generating Python code from SRV kortex_device_manager/SetPartNumberRevision
[ 22%] Generating Python code from SRV kortex_device_manager/SetIPv4Settings
[ 22%] Generating Javascript code from kortex_device_manager/ReadAllDevices.srv
[ 22%] Generating Python code from SRV kortex_device_manager/GetSafetyInformation
[ 22%] Generating Python code from SRV kortex_device_manager/ResetSafetyDefaults
[ 22%] Generating Python code from SRV kortex_device_manager/ClearAllSafetyStatus
[ 22%] Generating Python code from SRV kortex_device_manager/GetRunMode
[ 22%] Generating Python code from SRV kortex_device_manager/GetIPv4Settings
[ 22%] Generating Javascript code from kortex_device_manager/GetSafetyConfiguration.srv
[ 22%] Generating Python code from SRV kortex_device_manager/GetMACAddress
[ 22%] Generating Python code from SRV kortex_device_manager/SetSafetyEnable
[ 22%] Generating Python code from SRV kortex_device_manager/GetAllSafetyConfiguration
[ 22%] Generating Python code from SRV kortex_device_manager/ReadAllDevices
[ 22%] Generating Python code from SRV kortex_device_manager/GetSafetyConfiguration
[ 22%] Generating Javascript code from kortex_device_manager/RebootRequest.srv
[ 22%] Generating Python code from SRV kortex_device_manager/RebootRequest
[ 22%] Generating Javascript code from kortex_device_manager/SafetyTopic.srv
[ 22%] Generating Python code from SRV kortex_device_manager/SafetyTopic
[ 22%] Generating Python code from SRV kortex_device_manager/GetPartNumberRevision
[ 22%] Generating Javascript code from kortex_device_manager/GetPartNumberRevision.srv
[ 22%] Generating Javascript code from kortex_device_manager/GetAllSafetyInformation.srv
[ 22%] Generating Python code from SRV kortex_device_manager/GetAllSafetyInformation
[ 22%] Generating Python code from SRV kortex_device_manager/GetSerialNumber
[ 22%] Generating Python code from SRV kortex_device_manager/GetSafetyStatus
[ 22%] Generating Python code from SRV kortex_device_manager/GetModelNumber
[ 22%] Generating Python code from SRV kortex_device_manager/GetDeviceType
[ 22%] Generating Python code from SRV kortex_device_manager/GetBootloaderVersion
[ 22%] Generating Javascript code from kortex_device_manager/GetSerialNumber.srv
[ 22%] Generating Python code from SRV kortex_device_manager/SetMACAddress
[ 22%] Generating Python code from SRV kortex_device_manager/SetSerialNumber
[ 22%] Generating Python code from SRV kortex_device_manager/SetModelNumber
[ 22%] Generating Python code from SRV kortex_device_manager/GetSafetyEnable
[ 22%] Generating Javascript code from kortex_device_manager/GetSafetyStatus.srv
[ 22%] Generating Python code from SRV kortex_device_manager/SetSafetyConfiguration
[ 22%] Generating Python code from SRV kortex_device_manager/SetSafetyWarningThreshold
[ 23%] Generating Python code from SRV kortex_device_manager/SetSafetyErrorThreshold
[ 23%] Generating Python code from SRV kortex_device_manager/GetPartNumber
[ 23%] Generating Javascript code from kortex_device_manager/GetModelNumber.srv
[ 23%] Generating Python code from SRV kortex_device_manager/GetPowerOnSelfTestResult
[ 23%] Generating Javascript code from kortex_device_manager/GetDeviceType.srv
[ 23%] Generating Javascript code from kortex_device_manager/GetBootloaderVersion.srv
[ 24%] Generating Javascript code from kortex_device_manager/SetMACAddress.srv
[ 24%] Generating Javascript code from kortex_device_manager/SetSerialNumber.srv
[ 24%] Generating Javascript code from kortex_device_manager/SetModelNumber.srv
[ 24%] Generating Javascript code from kortex_device_manager/GetSafetyEnable.srv
[ 24%] Generating Javascript code from kortex_device_manager/SetSafetyConfiguration.srv
[ 24%] Generating Javascript code from kortex_device_manager/SetSafetyWarningThreshold.srv
[ 24%] Generating Javascript code from kortex_device_manager/SetSafetyErrorThreshold.srv
[ 24%] Generating Python msg __init__.py for kortex_device_manager
[ 24%] Generating Javascript code from kortex_device_manager/GetPartNumber.srv
[ 24%] Generating Javascript code from kortex_device_manager/GetPowerOnSelfTestResult.srv
[ 24%] Generating Python srv __init__.py for kortex_device_manager
[ 24%] Built target kortex_device_manager_generate_messages_nodejs
[ 24%] Built target kortex_device_manager_generate_messages_py
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
```

**Comment by sbrisebois** [comment] 2019-03-21 16:01
Hi kracon7,

This is a known issue and it's in the pipeline for the fix.

The problem you have is caused by an error in the example files. 
You have to modify the file api_cpp/examples/CMakeLists.txt : 

Add a # on the line : 
add_subdirectory(300-BaseGen3_low_level_bypass)

To have : 
#add_subdirectory(300-BaseGen3_low_level_bypass)

Then empty the build folder and re-try the cmake command.

Best,
Sylvain

**Comment by alexvannobel** [comment] 2019-03-21 16:49
Hi @kracon7 ,

For your catkin_make problem:

- I think you may be missing a pre-required step : the kortex api has to be downloaded and copied in the src/kortex_api folder as explained in this [readme](https://github.com/Kinovarobotics/ros_kortex/blob/master/kortex_api/readme.md).
- There seems to be a bug in the kortex_examples [CMakeLists.txt](https://github.com/Kinovarobotics/ros_kortex/blob/master/kortex_examples/CMakeLists.txt) where the executables don't specify the dependencies to the drivers, so they build before the . I'll open a PR to fix this, it should be straightforward.

Hope this helps,
Best,

Alex

**Comment by alexvannobel** [comment] 2019-03-21 17:00
#11

**Comment by kracon7** [comment] 2019-03-21 17:15
Hi @sbrisebois 
This solved the cmake issue for kortex-api. Thanks!

**Comment by alexvannobel** [comment] 2019-03-21 17:24
Hi @kracon7 ,

I just merged the PR so catkin_make should now build the packages just fine if you downloaded the API and put it in the right place. Can you test if the fix worked?

**Comment by kracon7** [comment] 2019-03-21 18:13
Hi @alexvannobel 
I put the downloaded api in kortex_api folder and removed /kortex_api/include/google/
```sh
jc@jc-Precision-5510:~/catkin_ws/src/ros_kortex/kortex_api$ ls
include  lib  readme.md
jc@jc-Precision-5510:~/catkin_ws/src/ros_kortex/kortex_api$ ls include/
client  client_stubs  common  messages

```

The error message is too long so I put it in a [google doc](https://docs.google.com/document/d/1X-jjZydtA8wVIjjgMRtKPzzB3KS1d5a17vTUWRTCgQY/edit?usp=sharing)

**Comment by alexvannobel** [comment] 2019-03-21 18:37
I just did a fresh checkout of the master branch, I downloaded the kortex_api from the Google Drive link in the readme and put it in the right place. I also made sure to remove ```build/``` and ```devel/``` folders and ran catkin_make and everything built just fine. 
Your errors seem related to Protobuf. 
- What is the output of ```protoc --version``` in a terminal window?
- Did you ```rm -rf build/ devel/``` before re-running ```catkin_make```?
- Could you try reinstalling it?

**Comment by hlamontagne** [comment] 2019-03-21 18:40
Hi @kracon7 Canyou verify your protobuf version?
protoc --version
You absolutely need to use the 3.5.1

**Comment by kracon7** [comment] 2019-03-22 00:28
@hlamontagne 
`protoc --version` gives `libprotoc 3.7.0`

@alexvannobel 
I did remove build and devel before catkin_make.
I will reinstall protobuf 3.5.1 and try again.

**Comment by kracon7** [comment] 2019-03-22 01:33
@sbrisebois @alexvannobel @hlamontagne 
I did `git checkout 860bd12` to swithc to branch 3.5.1.1 and everything else the same as the instruction.
`catkin_make` works now. Thanks!

**Comment by alexvannobel** [comment] 2019-03-22 03:21
Glad it worked!

**Closed by alexvannobel** 2019-03-22 03:21 UTC
