### ISSUE TITLE
How to register RGB image and depth image？

### ISSUE THREAD

**Issue by JingKangSun** [Kinovarobotics/ros_kortex#225] opened 2022-03-26 03:56 UTC
Hi, 

I get the RGB-Image by subscribing the topic '/camera/color/image_rect_color', Depth-Image by subscribing the topic '/camera/depth_registered/sw_registered/image_rect'.

When I use the RGB-Image and Depth-Image to get point cloud, I get the result as below：

ResultInRVIZ：

![RVIZ-Image](https://github.com/JingKangSun/video/blob/main/kk.png)

This show that RGB-Image and Depth-Image are not well registered, so is there a way to get relatively accurate registration results?

**Comment by felixmaisonneuve** [comment] 2022-04-04 14:00
Hi @JingKangSun,

I see you also have duplicated this issue in our ros_kortex_vision repo : 
https://github.com/Kinovarobotics/ros_kortex_vision/issues/9
which is also a duplicate of this other issue (in which you commented) : 
https://github.com/Kinovarobotics/ros_kortex_vision/issues/1

I will close this one and do my best to answer you in the second one (issue 1).

**Closed as completed by felixmaisonneuve** 2022-04-04 14:00 UTC
