### ISSUE TITLE
compiler not defined for compiler.libcxx

### ISSUE THREAD

**Issue by RaduCorcodel** [Kinovarobotics/ros_kortex#122] opened 2020-09-04 20:01 UTC
System: Ubuntu 16.04, fresh install of ROS-kinetic

Tried to install ros_kortex following the instructions and got this error message:

```-- Boost version: 1.58.0
-- +++ processing catkin package: 'kortex_driver'
-- ==> add_subdirectory(ros_kortex/kortex_driver)
CONAN_TARGET_PLATFORM is x86
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
-- kortex_driver: 408 messages, 254 services
-- Conan: checking conan executable in path
-- Conan: Found program /usr/local/bin/conan
-- Conan: Version found Conan version 1.23.0

-- Conan: Adding kinova_public remote repository (https://artifactory.kinovaapps.com/artifactory/api/conan/conan-public)
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Release;-s;compiler=gcc;-s;compiler.version=5;-s;compiler.libcxx=libstdc++11;-s;kortex_api_cpp:compiler=gcc;-s;kortex_api_cpp:compiler.version=5;-s;kortex_api_cpp:compiler.libcxx=libstdc++11
-- Conan executing: conan install /homes/user/kinova_workspace/src/ros_kortex/kortex_driver/conanfile.py -s build_type=Release -s compiler=gcc -s compiler.version=5 -s compiler.libcxx=libstdc++11 -s kortex_api_cpp:compiler=gcc -s kortex_api_cpp:compiler.version=5 -s kortex_api_cpp:compiler.libcxx=libstdc++11 -g=cmake --update
ERROR: compiler not defined for compiler.libcxx
Please define compiler value first too
CMake Error at ros_kortex/kortex_driver/cmake/conan.cmake:399 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  ros_kortex/kortex_driver/cmake/conan.cmake:485 (conan_cmake_install)
  ros_kortex/kortex_driver/CMakeLists.txt:70 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/homes/user/kinova_workspace/build/CMakeFiles/CMakeOutput.log".
See also "/homes/user/kinova_workspace/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed```

**Comment by alexvannobel** [comment] 2020-11-23 17:00
Hi @RaduCorcodel ,
Sorry for the long delay.

This is a weird error message. In [this issue](https://github.com/conan-io/conan/issues/615) it seems like an order problem but I've never seen that.
What's the output of `conan profile show default` in a terminal?

**Comment by tsoud** [comment] 2021-04-20 12:44
Hi, 
I'm running into this exact same issue. The output from `CMake` is identical to that of the original poster.
`ERROR: compiler not defined for compiler.libcxx`
`Please define compiler value first too`
`CMake Error at ros_kortex/kortex_driver/cmake/conan.cmake:399 (message):`
`  Conan install failed='1'`

This is the output from `conan profile show default`:
`[settings]`
`os=Linux`
`os_build=Linux`
`arch=x86_64`
`arch_build=x86_64`
`build_type=Release`
`compiler.libcxx=libstdc++11`
`[options]`
`[build_requires]`
`[env]`
`

After reviewing the issue referenced above, it doesn't seem that ordering (in the `install` command) is the problem: 
`-- Conan executing: conan install /home/user/directory/subdir/downloaded_robots/kinova_gen3/ros_ws/src/ros_kortex/kortex_driver/conanfile.py -s build_type=Release -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -s kortex_api_cpp:compiler=gcc -s kortex_api_cpp:compiler.version=5 -s kortex_api_cpp:compiler.libcxx=libstdc++11 -g=cmake --update` where `user/directory/subdir` is the parent directory. 

edit: I should also mention this is on ROS-noetic

Any recommendations?
Thanks

**Comment by polthergeist** [comment] 2021-04-22 16:50
Hi @tsoud and @RaduCorcodel ,
Could you try to install manually your conan profile using this command:
`conan install . --profile /abs/path/to/profile`
You can put your profile in a .cfg file that should look like this:
![image](https://user-images.githubusercontent.com/59037179/115753418-2e61ff80-a369-11eb-91bc-563458d9fcc3.png)
 You can modify those settings to match the one you need.

Keep me posted,

**Comment by tsoud** [comment] 2021-04-24 21:47
Hi @polthergeist,
Thanks for the advice. Unfortunately, I followed the recommendations and still got the same error. I'm sure I'm missing something but not sure where to look. 

Further info:
I added a robotics.cfg with the exact parameters you provided to my ~/.conan/profiles directory (this is also where the default config is). I ran `conan . --profile ~/.conan/profiles/robotics.cfg` from the directory suggested by the conan helpfile:
![image](https://user-images.githubusercontent.com/34865184/115973570-a2440980-a51b-11eb-826b-0950808eff75.png)

In this case, the directory ('.') containing `conanfile.py` is: /many/parent/dirs/src/ros_ws/src/ros_kortex/kortex_driver/ if I understood the instructions correctly.

Another important detail is that I'm running all this from within a conda environment. I don't know if this affects anything but it seems everything is set up correctly in the environment. Any other ideas welcome. Thanks in advance.

**Comment by felixmaisonneuve** [comment] 2021-06-18 15:18
Hi @tsoud,

I see your are using ROS Noetic. We do not officially support it yet, but I will be working on ROS Melodic -> ROS Noetic migration in the upcoming weeks. 

This error may be caused by incompatible version of Conan/ROS/Something else... 
Since I will be going through this process, I might have to deal with this. 

I will keep you informed here when we are going to release official support for ROS Noetic and maybe by then you will be able to try it and see if this error still occurs.

Regards,
Felix

**Comment by felixmaisonneuve** [comment] 2021-07-07 18:20
Hi @tsoud, 

We now officially support ROS Noetic and it can be cloned from here : https://github.com/Kinovarobotics/ros_kortex/tree/noetic-devel

Can you try again using this branch to see if this error still occurs?

@RaduCorcodel, do you still have an issue with conan? 

I will leave you both a couple of weeks and close this issue if I do not get an answer by then.

Regards, 
Felix

**Comment by tsoud** [comment] 2021-07-09 12:14
Hi @felixmaisonneuve,

Thanks for letting me know! I will give it a try and let you know.

Regards,
Tamer

**Comment by felixmaisonneuve** [comment] 2021-07-26 16:58
I will close this issue since the original post is getting pretty old.

@RaduCorcodel, if you still get an error, please fill the issue template and submit it. 
I will look at it and help you then

Thank you, 
Felix

**Closed as completed by felixmaisonneuve** 2021-07-26 16:58 UTC

**Comment by felixmaisonneuve** [comment] 2021-07-26 17:00
Similarly, @tsoud if you still get this issue, please create a new issue

**Comment by tsoud** [comment] 2021-07-28 16:33
> Similarly, @tsoud if you still get this issue, please create a new issue

Hi @felixmaisonneuve, 
Thank you, will do. I had to leave ROS for the time being and work on other things but will let the team know if anything else comes up.

**Comment by qdaicho** [comment] 2022-11-08 18:38
I was able to fix this error by running the following commands:

`conan profile update settings.compiler=gcc default`

`conan profile remove settings.compiler.libcxx default`

`conan profile show default`

output:

```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
[options]
[conf]
[build_requires]
[env]
```
