### ISSUE TITLE
catkin_make build failed on Ubuntu 20.04 with gcc 11

### ISSUE THREAD

**Issue by zehuilu** [Kinovarobotics/ros_kortex#259] opened 2022-10-17 19:11 UTC
## Description

I downloaded this repo and followed the instructions to build the whole repo. The build failed and popped many errors related to c++ headers. I post a few here for reference.

```
/usr/include/ignition/math6/gz/math/Helpers.hh:1059:28: error: ‘chrono_literals’ is not a namespace-name
 1059 |       using namespace std::chrono_literals;

/usr/include/sdformat-9.8/sdf/Param.hh:85:22: error: use of ‘auto’ in lambda parameter declaration only available with ‘-std=c++14’ or ‘-std=gnu++14’
   85 |     std::visit([&os](auto const &v)

/usr/include/sdformat-9.8/sdf/Param.hh:286:24: error: ‘is_same_v’ is not a member of ‘std’; did you mean ‘is_same’?
  286 |     if constexpr (std::is_same_v<T, bool>)

/usr/include/sdformat-9.8/sdf/Param.hh:426:17: error: ‘holds_alternative’ is not a member of ‘std’
  426 |     return std::holds_alternative<Type>(this->dataPtr->value);

/***/catkin_ws_noetic/src/ros_kortex/kortex_driver/src/non-generated/driver/cartesian_trajectory_action_server.cpp:146:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  146 |         std::this_thread::sleep_for(std::chrono::milliseconds(1000));

/***/catkin_ws_noetic/src/ros_kortex/kortex_driver/src/non-generated/driver/joint_trajectory_action_server.cpp:202:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
  202 |         std::this_thread::sleep_for(std::chrono::milliseconds(1000));

                 from /***/catkin_ws_noetic/src/ros_kortex/third_party/gazebo-pkgs/gazebo_version_helpers/src/GazeboVersionHelpers.cpp:1:
/usr/include/ignition/math6/gz/math/Helpers.hh:835:29: error: type/value mismatch at argument 1 in template parameter list for ‘template<long unsigned int _Int, class _Tp1, class _Tp2> constexpr typename std::tuple_element<_Int, std::pair<_Tp1, _Tp2> >::type& std::get(std::pair<_Tp1, _Tp2>&)’
  835 |         (std::get<Durations>(retval) =
```

I think it's caused by a different c++ compiler version. So I add a header file `#include <thread>` to `ros_kortex/kortex_driver/src/non-generated/driver/cartesian_trajectory_action_server.cpp` and `ros_kortex/kortex_driver/src/non-generated/driver/joint_trajectory_action_server.cpp`.

And I changed the c++ compiler setting as c++ 17 in two CMakeLists.txt, i.e. `ros_kortex/third_party/gazebo-pkgs/gazebo_grasp_plugin/CMakeLists.txt` and `ros_kortex/third_party/gazebo-pkgs/gazebo_version_helpers/CMakeLists.txt`. See [here](https://github.com/Kinovarobotics/ros_kortex/blob/noetic-devel/third_party/gazebo-pkgs/gazebo_grasp_plugin/CMakeLists.txt#L41-L51) and [here](https://github.com/Kinovarobotics/ros_kortex/blob/noetic-devel/third_party/gazebo-pkgs/gazebo_version_helpers/CMakeLists.txt#L37-L47) for original codes.

The following is what I changed,
```
# check c++17
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++17" COMPILER_SUPPORTS_CXX17)
if(COMPILER_SUPPORTS_CXX17)
  set(CMAKE_CXX_FLAGS "-std=c++17")
else()
  message(FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} has no C++17 support. Please use a different C++ compiler. Suggested solution: update the pkg build-essential ")
endif()
```

After I made these two changes, the errors disappeared and the repo was built successfully. Is it possible to make any changes on your side so that the noetic branch is more reliable to multiple gcc versions?

## Version

OS: Ubuntu 20.04.5 LTS
GCC version: 11.1.0
CMake: 3.16.3
ROS distribution : ROS Noetic
Branch and commit you are using : noetic-devel, a46606e

**Comment by felixmaisonneuve** [comment] 2022-10-26 17:51
Hi @zehuilu,

Sorry for the delay. 
I investigated the issue and added the modification (they will be merge soon). 
I would appreciate if you could test it as well to make sure everything works as intended.

I will close this issue once the modifications are merged to the noetic-branch

Regards,
Felix

**Closed as completed** 2022-12-15 20:42 UTC
